CREATE ROLE plus9_migrator
  LOGIN
  CREATEDB
  PASSWORD 'plus9_migrator_local';

CREATE ROLE plus9_app
  LOGIN
  PASSWORD 'plus9_app_local';

ALTER DATABASE "90plus9" OWNER TO plus9_migrator;
CREATE DATABASE "90plus9_test" OWNER plus9_migrator;

REVOKE ALL ON DATABASE "90plus9" FROM PUBLIC;
GRANT CONNECT ON DATABASE "90plus9" TO plus9_app;

REVOKE ALL ON DATABASE "90plus9_test" FROM PUBLIC;
GRANT CONNECT ON DATABASE "90plus9_test" TO plus9_app;

\connect 90plus9

REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO plus9_app;

ALTER DEFAULT PRIVILEGES FOR ROLE plus9_migrator IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO plus9_app;

ALTER DEFAULT PRIVILEGES FOR ROLE plus9_migrator IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO plus9_app;

\connect 90plus9_test

REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO plus9_app;

ALTER DEFAULT PRIVILEGES FOR ROLE plus9_migrator IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO plus9_app;

ALTER DEFAULT PRIVILEGES FOR ROLE plus9_migrator IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO plus9_app;
